import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navigation from "@/components/Navigation";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="scrollbar-thin scrollbar-thumb-cyan-600 scrollbar-track-[#171717] h-32 overflow-y-scroll"
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-zinc-100 selection:bg-cyan-300 selection:text-cyan-950`}
      >
        <div
          id="background"
          className="fixed top-0 z-[-2] h-full w-full bg-neutral-900 bg-[radial-gradient(ellipse_50%_70%_at_50%_-10%,rgba(22,78,99,0.4),rgba(255,255,255,0))] antialiased"
        ></div>
        <header>
          <Navigation />
        </header>
        <main className="mx-10 flex flex-col justify-center">{children}</main>
        <footer>Footer</footer>
      </body>
    </html>
  );
}
