/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import { useGLTF } from "@react-three/drei";

export function IsoScene(props) {
  const { nodes, materials } = useGLTF("/models/myiso_v5.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0.439, 0.452, 1.122]} scale={[0.135, 0.098, 0.474]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_2.geometry}
          material={materials.Monitor_Frame}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Schrank.geometry}
        material={materials.Cupboard}
        position={[0.278, 0.168, 0.333]}
        scale={[0.141, 0.087, 0.141]}
      />
      <group position={[0.376, 0.524, 0.364]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_1.geometry}
          material={materials.pc_case}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_2.geometry}
          material={materials.fan_ring}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_3.geometry}
          material={materials.fan_rgb_ring}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_4.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_5.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_6.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_7.geometry}
          material={materials["Material.008"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rug.geometry}
        material={materials["Monitor_Frame.001"]}
        position={[1.024, 0.082, 1.171]}
        scale={[0.47, 0.636, 0.701]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Schrank001.geometry}
        material={materials.Cupboard}
        position={[0.211, 0.14, 1.857]}
        scale={[0.093, 0.058, 0.093]}
      />
      <group position={[1, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials["Material.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials["Material.016"]}
        />
      </group>
      <group position={[0.155, 1.091, 1.124]} scale={[0.075, 0.01, 0.612]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016_2.geometry}
          material={materials.shelf_light_inside}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016_3.geometry}
          material={materials.shelf_light_outside}
        />
      </group>
      <group
        position={[0.15, 1.153, 1.002]}
        rotation={[-Math.PI, 1.523, -Math.PI]}
        scale={[0.092, 0.054, 0.054]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_1.geometry}
          material={materials.cat_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_2.geometry}
          material={materials["cat_eye.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_3.geometry}
          material={materials.cat_hair}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leg_01.geometry}
        material={materials.Table_Foot}
        position={[0.335, 0.441, 1.146]}
        scale={[0.25, 0.01, 0.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leg_02.geometry}
        material={materials.Table_Foot}
        position={[0.326, 0.441, 1.146]}
        scale={[0.25, 0.01, 0.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leg_03.geometry}
        material={materials.Table_Foot}
        position={[0.326, 0.441, 1.146]}
        scale={[0.25, 0.01, 0.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leg_04.geometry}
        material={materials.Table_Foot}
        position={[0.326, 0.441, 1.146]}
        scale={[0.25, 0.01, 0.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plate.geometry}
        material={materials["Table Plate"]}
        position={[0.326, 0.441, 1.146]}
        scale={[0.25, 0.01, 0.6]}
      />
      <group
        position={[0.148, 0.608, 1.563]}
        rotation={[0, 0.244, 0]}
        scale={0.015}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_1.geometry}
          material={materials.Monitor_Frame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_2.geometry}
          material={materials.scene_samurai_champloo}
        />
      </group>
      <group position={[0.097, 0.608, 1.115]} scale={0.015}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_1.geometry}
          material={materials.Monitor_Frame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_2.geometry}
          material={materials.scene_blender_edit}
        />
      </group>
      <group
        position={[0.152, 0.608, 0.671]}
        rotation={[0, -0.244, 0]}
        scale={0.015}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_1.geometry}
          material={materials.Monitor_Frame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_2.geometry}
          material={materials.Monitor_Frame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_3.geometry}
          material={materials.scene_vis_code}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Foot.geometry}
        material={materials["Material.005"]}
        position={[0.806, 0.165, 1.188]}
        rotation={[0, -0.049, 0]}
        scale={0.027}
      />
      <group
        position={[0.665, 0.101, 1.084]}
        rotation={[0, -0.049, 0]}
        scale={1.715}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_1.geometry}
          material={materials.Monitor_Frame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_2.geometry}
          material={materials.Rolladen_Kiste}
        />
      </group>
      <group
        position={[0.702, 0.101, 1.329]}
        rotation={[0, -0.468, 0]}
        scale={1.715}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_1.geometry}
          material={materials.Monitor_Frame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_2.geometry}
          material={materials.Rolladen_Kiste}
        />
      </group>
      <group
        position={[0.947, 0.101, 1.292]}
        rotation={[0, -1.159, 0]}
        scale={1.715}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_1.geometry}
          material={materials.Monitor_Frame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_2.geometry}
          material={materials.Rolladen_Kiste}
        />
      </group>
      <group
        position={[0.91, 0.101, 1.047]}
        rotation={[0, 0.287, 0]}
        scale={1.715}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_1.geometry}
          material={materials.Monitor_Frame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_2.geometry}
          material={materials.Rolladen_Kiste}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.seat.geometry}
        material={materials.Chair_Seat}
        position={[0.806, 0.317, 1.185]}
        rotation={[0, -0.049, 0]}
        scale={[0.125, 0.013, 0.111]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={materials["Material.001"]}
        position={[0.403, 0.138, 1.686]}
        scale={0.058}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane019.geometry}
        material={nodes.Plane019.material}
        position={[0.399, 0.236, 0.356]}
        scale={[0.082, 0.109, 0.109]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane020.geometry}
        material={nodes.Plane020.material}
        position={[0.4, 0.161, 0.294]}
        rotation={[0, 0.181, 0]}
        scale={[0.082, 0.109, 0.109]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane021.geometry}
        material={nodes.Plane021.material}
        position={[0.399, 0.238, 0.273]}
        rotation={[0, -0.089, 0]}
        scale={[0.082, 0.109, 0.109]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane022.geometry}
        material={nodes.Plane022.material}
        position={[0.399, 0.241, 0.332]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.082, 0.109, 0.109]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane023.geometry}
        material={nodes.Plane023.material}
        position={[0.286, 0.242, 0.37]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.082, 0.109, 0.109]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane024.geometry}
        material={nodes.Plane024.material}
        position={[0.399, 0.241, 0.356]}
        scale={[0.082, 0.109, 0.109]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane025.geometry}
        material={nodes.Plane025.material}
        position={[0.431, 0.248, 0.273]}
        rotation={[0, 0.364, 0]}
        scale={[0.082, 0.109, 0.109]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane026.geometry}
        material={nodes.Plane026.material}
        position={[0.425, 0.171, 1.635]}
        rotation={[0.752, -0.417, -0.984]}
        scale={[0.037, 0.05, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane027.geometry}
        material={nodes.Plane027.material}
        position={[0.394, 0.137, 1.71]}
        rotation={[-1.634, -0.719, -2.854]}
        scale={[0.037, 0.05, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane028.geometry}
        material={nodes.Plane028.material}
        position={[0.44, 0.152, 1.683]}
        rotation={[-0.623, -1.061, -2.034]}
        scale={[0.037, 0.05, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane029.geometry}
        material={nodes.Plane029.material}
        position={[0.4, 0.21, 1.688]}
        rotation={[1.984, -0.219, -0.36]}
        scale={[0.037, 0.05, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane030.geometry}
        material={materials["Material.011"]}
        position={[0.122, 0.475, 1.294]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.019}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane031.geometry}
        material={materials["Material.012"]}
        position={[0.122, 0.475, 1.246]}
        rotation={[-0.017, 0, -1.569]}
        scale={0.019}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane032.geometry}
        material={materials["Material.011"]}
        position={[0.122, 0.475, 1.001]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.019}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.Leaf}
        position={[1.602, 0.713, 0.247]}
        rotation={[0.007, -0.145, -0.308]}
        scale={[0.295, 0.168, 0.168]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials.Leaf}
        position={[1.72, 0.768, 0.368]}
        rotation={[0.2, 0.57, -0.813]}
        scale={[0.24, 0.137, 0.137]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials.Leaf}
        position={[2.07, 0.623, 0.194]}
        rotation={[-3.126, -0.138, -3.025]}
        scale={[0.295, 0.168, 0.168]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials.Leaf}
        position={[1.802, 0.819, 0.194]}
        rotation={[0, -1.436, -1.112]}
        scale={[0.185, 0.105, 0.105]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials.Leaf}
        position={[1.817, 0.649, 0.436]}
        rotation={[0, 1.429, 0]}
        scale={[0.213, 0.121, 0.121]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials.Leaf}
        position={[2.025, 0.702, 0.421]}
        rotation={[-Math.PI, 0.796, 2.872]}
        scale={[0.27, 0.153, 0.153]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials.Leaf}
        position={[2.061, 0.764, 0.345]}
        rotation={[-2.888, 0.423, 2.579]}
        scale={[0.295, 0.168, 0.168]}
      />
      <group position={[1.826, 0.08, 0.253]} scale={-0.131}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_1.geometry}
          material={materials.Plant_Topf}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_2.geometry}
          material={materials.Topf_erde}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_3.geometry}
          material={materials.Stamm}
        />
      </group>
      <group
        position={[0.994, 1.486, 0.102]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.022, 0.317, 0.022]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_1.geometry}
          material={materials.Rolladen_Kiste}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_2.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_3.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_4.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials._keyboard}
        position={[0.439, 0.466, 1.146]}
        rotation={[0, 0, -0.092]}
        scale={-0.008}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials._keyboard}
        position={[0.4, 0.47, 1.167]}
        rotation={[0, 0, -0.092]}
        scale={-0.008}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials._keyboard}
        position={[0.4, 0.47, 1.401]}
        rotation={[0, 0, -0.092]}
        scale={-0.008}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials._keyboard}
        position={[0.419, 0.468, 1.401]}
        rotation={[0, 0, -0.092]}
        scale={-0.008}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials._keyboard}
        position={[0.439, 0.466, 1.398]}
        rotation={[0, 0, -0.092]}
        scale={[-0.008, -0.008, -0.011]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials._keyboard}
        position={[0.458, 0.465, 1.369]}
        rotation={[0, 0, -0.092]}
        scale={-0.008}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials._keyboard}
        position={[0.458, 0.465, 1.394]}
        rotation={[0, 0, -0.092]}
        scale={[-0.008, -0.008, -0.014]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials._keyboard}
        position={[0.477, 0.463, 1.395]}
        rotation={[0, 0, -0.092]}
        scale={[-0.008, -0.008, -0.013]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials._keyboard}
        position={[0.477, 0.463, 1.365]}
        rotation={[0, 0, -0.092]}
        scale={[-0.008, -0.008, -0.013]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials._keyboard}
        position={[0.477, 0.463, 1.335]}
        rotation={[0, 0, -0.092]}
        scale={[-0.008, -0.008, -0.013]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials._keyboard}
        position={[0.4, 0.47, 1.14]}
        rotation={[0, 0, -0.092]}
        scale={[-0.008, -0.008, -0.014]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials._keyboard}
        position={[0.458, 0.465, 1.115]}
        rotation={[0, 0, -0.092]}
        scale={-0.008}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={materials._keyboard}
        position={[0.458, 0.465, 1.096]}
        rotation={[0, 0, -0.092]}
        scale={-0.008}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials._keyboard}
        position={[0.438, 0.466, 1.096]}
        rotation={[0, 0, -0.092]}
        scale={-0.008}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={materials._keyboard}
        position={[0.419, 0.468, 1.096]}
        rotation={[0, 0, -0.092]}
        scale={-0.008}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials._keyboard}
        position={[0.399, 0.47, 1.096]}
        rotation={[0, 0, -0.092]}
        scale={-0.008}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={materials._keyboard}
        position={[0.477, 0.463, 1.115]}
        rotation={[0, 0, -0.092]}
        scale={-0.008}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={materials._keyboard}
        position={[0.477, 0.463, 1.096]}
        rotation={[0, 0, -0.092]}
        scale={-0.008}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={materials._keyboard}
        position={[0.477, 0.463, 1.154]}
        rotation={[0, 0, -0.092]}
        scale={-0.008}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={materials._keyboard}
        position={[0.477, 0.463, 1.135]}
        rotation={[0, 0, -0.092]}
        scale={-0.008}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        material={materials._keyboard}
        position={[0.477, 0.463, 1.243]}
        rotation={[0, 0, -0.092]}
        scale={-0.008}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={materials._keyboard}
        position={[0.429, 0.467, 1.116]}
        rotation={[0, 0, -0.092]}
        scale={[0.019, 0.008, 0.008]}
      />
      <group
        position={[0.433, 0.46, 1.375]}
        rotation={[0, 0, -0.092]}
        scale={[-0.046, -0.003, -0.039]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube043.geometry}
          material={materials.Monitor_Frame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube043_1.geometry}
          material={materials.keybord_backlit}
        />
      </group>
      <group position={[0.354, 0.478, 1.672]} scale={0.026}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011.geometry}
          material={materials.mug}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011_1.geometry}
          material={materials.coffee}
        />
      </group>
      <group
        position={[0.354, 0.452, 1.673]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.038, 0.001, 0.038]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder012.geometry}
          material={materials.pc_case}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder012_1.geometry}
          material={materials["Material.013"]}
        />
      </group>
      <group
        position={[0.153, 1.187, 1.317]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.063, 0.084, 0.019]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube044.geometry}
          material={materials.book_cover_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube044_1.geometry}
          material={materials.book_pages}
        />
      </group>
      <group
        position={[0.153, 1.187, 1.364]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.063, 0.084, 0.019]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube045.geometry}
          material={materials["book_cover_1.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube045_1.geometry}
          material={materials.book_pages}
        />
      </group>
      <group
        position={[0.153, 1.168, 1.406]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.052, 0.07, 0.016]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube046.geometry}
          material={materials["book_cover_1.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube046_1.geometry}
          material={materials.book_pages}
        />
      </group>
      <group
        position={[0.153, 1.122, 1.518]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[0.063, 0.084, 0.019]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube047.geometry}
          material={materials.book_cover_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube047_1.geometry}
          material={materials.book_pages}
        />
      </group>
      <group
        position={[0.153, 1.187, 0.581]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.063, 0.084, 0.019]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048.geometry}
          material={materials.book_cover_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube048_1.geometry}
          material={materials.book_pages}
        />
      </group>
      <group
        position={[0.153, 1.187, 0.629]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.063, 0.084, 0.019]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube049.geometry}
          material={materials["book_cover_1.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube049_1.geometry}
          material={materials.book_pages}
        />
      </group>
      <group
        position={[0.153, 1.168, 0.671]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.052, 0.07, 0.016]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube050.geometry}
          material={materials["book_cover_1.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube050_1.geometry}
          material={materials.book_pages}
        />
      </group>
      <group
        position={[0.153, 1.187, 0.716]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.063, 0.084, 0.019]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube051.geometry}
          material={materials.book_cover_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube051_1.geometry}
          material={materials.book_pages}
        />
      </group>
      <group
        position={[0.153, 1.168, 0.759]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.052, 0.07, 0.016]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052.geometry}
          material={materials["book_cover_1.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052_1.geometry}
          material={materials.book_pages}
        />
      </group>
      <group position={[0.134, 1.514, 1.845]} scale={[0.054, 0.073, 0.054]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053.geometry}
          material={materials.speaker_box}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_1.geometry}
          material={materials.speaker_cover}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_2.geometry}
          material={materials.speaker_band}
        />
      </group>
      <group position={[0.134, 1.514, 0.318]} scale={[0.054, 0.073, 0.054]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054.geometry}
          material={materials.speaker_box}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_1.geometry}
          material={materials.speaker_cover}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_2.geometry}
          material={materials.speaker_band}
        />
      </group>
      <group position={[0.457, 0.462, 0.938]} scale={[0.044, 0.004, 0.034]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube055.geometry}
          material={materials._keyboard}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube055_1.geometry}
          material={materials.mouse_rgb}
        />
      </group>
      <group
        position={[0.444, 0.468, 1.674]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.016, 0.006, 0.085]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube057.geometry}
          material={materials.earphone_frame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube057_1.geometry}
          material={materials.earphone_ear}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus.geometry}
        material={materials.earphone_frame}
        position={[0.354, 0.476, 1.673]}
        rotation={[0.114, 0, 0]}
        scale={0.037}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus001.geometry}
        material={materials.earphone_frame}
        position={[0.354, 0.463, 1.673]}
        rotation={[-0.255, 0, 0]}
        scale={0.037}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus002.geometry}
        material={materials.earphone_frame}
        position={[0.354, 0.49, 1.673]}
        rotation={[-0.245, 0, 0]}
        scale={0.037}
      />
      <group
        position={[0.492, 0.452, 1.673]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.061, 0.002, 0.061]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013.geometry}
          material={materials.pc_case}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_1.geometry}
          material={materials["Material.013"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        position={[0.211, 0.265, 1.857]}
        scale={0.036}
      />
      <group position={[0.211, 0.278, 1.857]} scale={[0.002, 0.069, 0.002]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015.geometry}
          material={materials.rose_stiel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015_1.geometry}
          material={materials.rosebud_rest}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={materials.rose_bud_leaf}
        position={[0.242, 0.23, 1.902]}
        scale={-0.015}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials.rose_bud_leaf}
        position={[0.265, 0.08, 1.973]}
        scale={-0.013}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={materials.rose_bud_leaf}
        position={[0.231, 0.231, 1.926]}
        rotation={[-0.017, -0.488, -0.103]}
        scale={-0.017}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010.geometry}
        material={materials.rose_bud_leaf}
        position={[0.259, 0.234, 1.92]}
        rotation={[3.13, 0.793, -Math.PI]}
        scale={-0.014}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials.rose_bud_leaf}
        position={[0.201, 0.233, 1.926]}
        rotation={[0.089, 0.749, 0]}
        scale={-0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={materials.rose_bud_leaf}
        position={[0.214, 0.23, 1.904]}
        rotation={[0, -0.908, 0]}
        scale={-0.015}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={materials.rose_bud_leaf}
        position={[0.229, 0.08, 1.979]}
        rotation={[Math.PI, -0.552, Math.PI]}
        scale={-0.013}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={materials.rose_bud_leaf}
        position={[0.18, 0.231, 1.897]}
        rotation={[3.1, 0.343, -3.14]}
        scale={-0.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube040.geometry}
        material={materials["Material.010"]}
        position={[1.021, 0.21, 0.131]}
        scale={[0.28, 0.108, 0.048]}
      />
      <group
        position={[0.206, 0.284, 1.857]}
        rotation={[0, 0.311, 0]}
        scale={[0.002, 0.069, 0.002]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.rose_stiel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_2.geometry}
          material={materials.rosebud_rest}
        />
      </group>
      <group
        position={[0.201, 0.281, 1.864]}
        rotation={[0, -0.169, 0]}
        scale={[0.002, 0.069, 0.002]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007_1.geometry}
          material={materials.rose_stiel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007_2.geometry}
          material={materials.rosebud_rest}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane015.geometry}
        material={materials.rose_bud_leaf}
        position={[0.258, 0.23, 1.889]}
        rotation={[3.1, 0.343, -3.14]}
        scale={-0.009}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane016.geometry}
        material={materials.rose_bud_leaf}
        position={[0.251, 0.242, 1.899]}
        rotation={[3.042, 1.163, -3.063]}
        scale={-0.009}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane017.geometry}
        material={materials.rose_bud_leaf}
        position={[0.155, 0.231, 1.929]}
        rotation={[3.042, 1.163, -3.063]}
        scale={-0.009}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane018.geometry}
        material={materials.rose_bud_leaf}
        position={[0.232, 0.275, 1.898]}
        rotation={[2.729, 0.185, -2.062]}
        scale={-0.009}
      />
      <group
        position={[0.153, 1.168, 1.406]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.052, 0.07, 0.016]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_1.geometry}
          material={materials["book_cover_1.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_2.geometry}
          material={materials.book_pages}
        />
      </group>
    </group>
  );
}
useGLTF.preload("/models/myiso_v5.glb");
